name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci

      - run: npm run build
        env:
          TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TURBO_TEAM: rocketseat

      - name: Deploy Storybook
        working-directory: ./packages/docs
        run: npx storybook-to-ghpages --ci --existing-output-dir=storybook-static --git-remote=https://x-access-token:${{ secrets.MY-PAT }}@github.com/kjunior-dev/05-design-system.git
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}



